services:
  user-service:
    image:
      22i1331/user-service
    restart: always
    environment:
      USER_DB_URL: postgresql://zohaib:1122@user_db:5432/userdb
      SECRET_KEY: your-secure-key-123
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - user_db

  event-service:
    image:
      22i1331/event-service
    restart: always
    environment:
      MONGO_URI : mongodb://mongo_db:27017
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongo_db

  booking-service:
    image:
      22i1331/booking-service
    restart: always
    environment:
      BOOKING_DB_URL: postgresql://zohaib:1122@booking_db:5432/bookingdb
      FLASK_SECRET_KEY: your-secret-key
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - booking_db

  notification-service:
    image:
      22i1331/notification-service
    restart: always
    ports:
      - "5004:5004"
    environment:
      MONGO_URL : mongo_db
      MONGO_PORT: 27017
      MONGO_DB: notifications_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mydevops.service@gmail.com
      MAIL_PASSWORD: yfqs lyve tsyn joyl

    networks:
      - app-network
    depends_on:
      - rabbitmq
      - mongo_db


  booking_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: zohaib
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: bookingdb
    ports:
      - "5435:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  user_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: zohaib
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    networks:
      - app-network
    volumes:
      - user-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  mongo_db:
    image: mongo:6.0
    restart: always
  
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  mongo-data:
  user-data: