apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: 22i1331/event-service
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: event-config
                  key: MONGO_URI
